from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class ExportService:
    """Generates a local placeholder report file for MVP."""

    def generate_placeholder_report(self, output_dir: Path, job_id: str, topic: str | None, payload: Any) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / "report.txt"

        content = [
            "APA Report (MVP Placeholder)",
            "",
            f"Job ID: {job_id}",
            f"Topic: {topic or 'Untitled'}",
            "",
            "Input Payload:",
            json.dumps(payload if payload is not None else {}, indent=2, default=str),
            "",
            "This is a placeholder report generated by the worker MVP.",
        ]
        output_path.write_text("\n".join(content), encoding="utf-8")
        return output_path
